---
- hosts: all
  roles:
    - role: '{{playbook_dir}}'
      stunnel_config_options:
        foreground: yes
      stunnel_config_apps:
        - name: example-redis-server
          secrets_dir: /secrets/tls
          accept:
            ty: ip
            bind: '0.0.0.0'
            port: 106379
          connect:
            ty: ip
            host: localhost
            port: 6379
        - name: example-redis-client
          mode: client
          secrets_dir: /secrets/tls
          accept:
            ty: ip
            bind: localhost
            port: 6379
          connect:
            ty: ip
            host: redis.example.com
            port: 106379
